### ISSUE TITLE
Allow adhoc explorers [APE-1151]

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/ape-etherscan#95]
### Overview

one step we can take to help lessen the debt of adding new networks:

allow setting arbitrary explorer URLS for networks that may or not exists:

### Specification

```yaml
etherscan:
  host_map:
    foo_net: "https://mainnet-fooscan.io"
```

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.
